### ISSUE TITLE
exception with unknown problem type

### ISSUE THREAD

**Issue by omnibasissupport** [PKISharp/ACMESharpCore#34]
public enum ProblemType is missing enum for orderNotReady

Here is exception we get
Error: System.ArgumentException: Requested value 'orderNotReady' was not found.
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at ACMESharp.Protocol.AcmeProtocolException.Init(Problem problem)
   at ACMESharp.Protocol.AcmeProtocolException..ctor(String message, Problem problem)
   at ACMESharp.Protocol.AcmeProtocolClient.DecodeResponseErrorAsync(HttpResponseMessage resp, String message, String opName)
   at ACMESharp.Protocol.AcmeProtocolClient.SendAcmeAsync(Uri uri, HttpMethod method, Object message, HttpStatusCode[] expectedStatuses, Boolean skipNonce, Boolean skipSigning, Boolean includePublicKey, CancellationToken cancel, String opName)
   at ACMESharp.Protocol.AcmeProtocolClient.FinalizeOrderAsync(String orderFinalizeUrl, Byte[] derEncodedCsr, CancellationToken cancel)

**Comment by WouterTinus** [comment]
I just submitted a PR for this, ran into the issue myself: https://github.com/PKISharp/ACMESharpCore/pull/40

**Comment by ebekker** [comment]
I believe this is addressed by #40, no?
